apiVersion: v1
kind: Service
metadata:
  name: nodejs-ts
  namespace: nodejs-ts
spec:
  selector:
    app: nodejs-ts
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
